[ui] add support for selecting multiple nodes at once
alicevision/meshroom pull request #1227
Opened 2021-01-15 20:33 UTC by ChemicalXandco

## Description

The ability to select multiple nodes at once improves the efficiency of using the graph editor. I have tried to make the node selection behave similar to blender. The box select widget is used by dragging with the left mouse button. The main selected node is slightly brighter than the other selected nodes and has a blue border.
![Screenshot_20210115_202417](https://user-images.githubusercontent.com/32775248/104775236-ed59be00-576f-11eb-86a7-8d67343251a0.png)
![Screenshot_20210115_193313](https://user-images.githubusercontent.com/32775248/104770693-e54a5000-5768-11eb-9e90-0024d2e52b1e.png)

## Features list

- select multiple nodes at once
- use of control key modifier to select multiple nodes
- use of box select widget to select multiple nodes
- duplicate selected nodes
- remove selected nodes
- delete data of selected nodes
- move selected nodes together

(Resolves some points on #269)

2021-01-22 22:24 UTC, fabiencastan commented
I often get this error when manipulating nodes in the GraphEditor:
```
Traceback (most recent call last):
  File "C:\dev\meshroom\meshroom\common\qt.py", line 190, in remove
    raise ValueError("QObjectListModel.remove(obj) : obj not in list")
ValueError: QObjectListModel.remove(obj) : obj not in list
[2021-01-22 23:22:10,394][WARNING] file:///C:/dev/meshroom/meshroom/ui/qml/GraphEditor/GraphEditor.qml:446: Error: QObjectListModel.remove(obj) : obj not in list
```

2021-01-25 10:16 UTC, fabiencastan requested changes
Thanks for the really cool PR!
I have added few notes to clean the code before integration.

2021-01-25 10:16 UTC, fabiencastan commented on meshroom/ui/commands.py
> +class DuplicateNodeListCommand(_DuplicateNodes):
Don't need to have 2 classes to do it with one of multiple nodes and inheritance, etc.
Either we keep `DuplicateNodeListCommand` and always use it (even for a single node) or keep `DuplicateNodeCommand` and group the commands for multiple nodes.

2021-04-13 19:54 UTC, fabiencastan commented
Small behavior problem in this configuration (duplicate nodes and nodes behind):
![image](https://user-images.githubusercontent.com/153585/114612271-37383e80-9ca2-11eb-8fb4-9de363de657a.png)

It gives:
![image](https://user-images.githubusercontent.com/153585/114612355-5505a380-9ca2-11eb-86a9-ebefd854eb36.png)

While the simple duplicate nodes:
![image](https://user-images.githubusercontent.com/153585/114612468-76668f80-9ca2-11eb-941e-0134bd9c2e3b.png)

Gives the correct result but with a strange selection:
![image](https://user-images.githubusercontent.com/153585/114612592-9dbd5c80-9ca2-11eb-85df-0975c4ea6f93.png)

2021-04-13 19:57 UTC, fabiencastan commented
It would be great the replace the "Alt+click" to select all the nodes after (instead of duplicating the nodes).
So if we want to move a node and all nodes connected behind it (a fairly common need), it would be simple.

2021-04-13 23:06 UTC, fabiencastan commented
Regarding the selection, I think we should clear the selection and select all the newly created nodes.

2021-04-13 23:09 UTC, fabiencastan commented
Really great PR, this is a life changer!
Looking forward to be able to merge it.

2021-04-16 14:21 UTC, ChemicalXandco commented
> Small behavior problem in this configuration (duplicate nodes and nodes behind)

I agree that this does not behave right. Should I remove the options '_ from here' or should I rework them to include the other selected nodes? I think that removing those options and relying on alt + click to select the following nodes is more intuitive than having these options that operate on some nodes that are **not** selected. What do you think @fabiencastan?

2021-04-16 14:50 UTC, fabiencastan commented
Good question. I agree that's redundant and makes two ways to do the same.
But, on the other hand, I think it's still useful to have the "from here" option as it's visual and do not require to know the keyboard shortcuts.
Also alt/shift/ctrl can be problematic in remote, or on some linux alt could be used by the os to move the window, etc.

2021-04-20 20:38 UTC, natowi commented
Love it :)

![demo](https://user-images.githubusercontent.com/8138537/115459411-4fbad280-a227-11eb-9b9c-b4ea74de855b.GIF)

Only a few minor layout issues https://github.com/alicevision/meshroom/issues/1389

2021-04-23 11:39 UTC, fabiencastan commented
@ChemicalXandco Is it ready for review? Or are you still working on it?

2021-04-23 16:13 UTC, ChemicalXandco commented
It is ready

2021-05-03 21:31 UTC, fabiencastan approved these changes

2021-05-03 21:42 UTC, fabiencastan commented
Great work!

2021-05-03 21:42 UTC, merged