Add nl means denoising open cv in image processing node
alicevision/Meshroom pull request #1719
Opened 2022-06-29 09:42 UTC by tanstella

## Description
Added parameters in ImageProcessing node for denoising by OpenCV (NLMeans denoising)

## Features list

## Implementation remarks

2022-07-12 08:17 UTC, fabiencastan requested changes
Need to delete stale files from git.

2022-08-10 09:57 UTC, tanstella commented
Done

2022-12-05 14:59 UTC, cbentejac commented on meshroom/nodes/aliceVision/ImageProcessing.py
> +        desc.GroupAttribute(name="nlmFilter", label="NL Means Denoising", description="NL Means Denoising Parameters.", joinChar=":", groupDesc=[
Done.

2022-12-13 17:49 UTC, fabiencastan approved these changes

2022-12-13 21:48 UTC, merged