Add cgroups support to meshroom
alicevision/Meshroom pull request #1836
Opened 2022-12-02 09:45 UTC by servantftechnicolor

CGroups on linux may limit the memory and the number of cpus

Without getting the specific information about these limits, we may overshoot our memory usage and core usage, creating crashes.

This PR will read the values as specified by the specifications

2022-12-05 13:03 UTC, fabiencastan commented
We need to find a way for nodes to declare if they supports these arguments or rely on environment variables.
We have many nodes launching external commands (like blender).
We could for instance create an intermediate class for AVCommandLineNode.

2022-12-05 13:56 UTC, mh0g commented
we could use a  chunk.node.nodeDesc.commandLine.startswith("aliceVision_") to do this only on the proper nodes

2022-12-05 14:06 UTC, mh0g approved these changes

2022-12-05 14:07 UTC, mh0g commented
a warning in the log when the feature is used may be usefull

2022-12-07 15:10 UTC, fabiencastan commented on meshroom/core/cgroup.py
> +    except IOError:
OSError

2022-12-07 15:13 UTC, fabiencastan requested changes

2022-12-07 15:13 UTC, fabiencastan commented on meshroom/core/desc.py
> +        memSize = cgroup.getCgroupMemorySize()
This is a static information that should be estimated once for the lifetime of the session and not each time we evaluate the command line per node.

2022-12-08 07:42 UTC, fabiencastan commented on meshroom/core/cgroup.py
> +def parseNumericList(str):
str is a python keyword, it would be good to rename this variable.

2022-12-08 07:43 UTC, fabiencastan commented on meshroom/core/desc.py
> +        str = super(AVCommandLineNode, self).buildCommandLine(chunk)
same

2022-12-08 08:37 UTC, fabiencastan approved these changes

2022-12-08 08:37 UTC, merged