[ui] Viewer2D: support all Exif orientation tags
alicevision/Meshroom pull request #1857
Opened 2022-12-29 14:25 UTC by mugulmd

## Description

The goal of this PR is to support all [Exif orientation tags](http://sylvana.net/jpegcrop/exif_orientation.html) in the 2D viewer, which only handles tags 6 and 8 at the moment.

We also solved a bug with the features viewer not being at the right position with some orientation tag (noticed with orientation tag 6): 
![orientation_bug_small](https://user-images.githubusercontent.com/70104194/209966351-153ff85e-379c-4441-b8a0-1ccde21b1a6b.png)
## Implementation remarks

Historically the 8bit viewer had to be handled differently than the other viewers because it is backed by Qt Images which handle orientation at the C++ level (therefore in the qtAliceVisionImageIO plugin in our case). 
This automatic transform has been disabled to make sure we can control all viewers with the same mechanism.

## Tests

- tested float viewer, 8bit viewer and features viewer on a set of images with no orientation tag
- tested float viewer, 8bit viewer and features viewer on a set of images with orientation tag 6
- tested float viewer and 8bit viewer on a [set of images containing all orientation tags](https://github.com/recurser/exif-orientation-examples)

## TODO

- test features viewer on more orientation tags
- test the other viewers: panorama, fisheye circle, color checker

2023-01-03 08:46 UTC, cbentejac requested changes
I tested this PR with the following images (https://github.com/recurser/exif-orientation-examples) and I noticed some issues for orientations 5 to 8, both in portrait and landscape images.

In landscape, the images with orientation tags of 5 and higher are "zoomed out" and displaced (not centered in the viewer). In portrait, it is the opposite: images with orientation tags of 5 and higher are "zoomed in". 

I haven't checked in details where this might be coming from (maybe there is a specific issue with these images). With regular random images of different orientations, I didn't notice such an obvious displacement (but I noticed that images in general seem to be zoomed in, although it seems that this already occurred on the "develop" branch), and the feature viewer displacement that occurred for orientation tag 6 was fixed.

2023-01-03 08:46 UTC, cbentejac commented on meshroom/ui/qml/Controls/ExifOrientedViewer.qml
> +    transform: [
There is an indentation issue here, there are more spaces for the properties than for the `transform`.

2023-01-03 17:30 UTC, mugulmd commented
> I tested this PR with the following images (https://github.com/recurser/exif-orientation-examples) and I noticed some issues for orientations 5 to 8, both in portrait and landscape images.
> 
> In landscape, the images with orientation tags of 5 and higher are "zoomed out" and displaced (not centered in the viewer). In portrait, it is the opposite: images with orientation tags of 5 and higher are "zoomed in".
> 
> I haven't checked in details where this might be coming from (maybe there is a specific issue with these images). With regular random images of different orientations, I didn't notice such an obvious displacement (but I noticed that images in general seem to be zoomed in, although it seems that this already occurred on the "develop" branch), and the feature viewer displacement that occurred for orientation tag 6 was fixed.

Should be fixed now :)

2023-01-03 17:33 UTC, fabiencastan commented on meshroom/ui/qml/Viewer/Viewer2D.qml
> +                             imgContainer.image.height;
`
let globalOrientation = ["5", "6", "7", "8"].includes(imgContainer.orientationTag);
let orientedWidth = globalOrientation ? imgContainer.image.height : imgContainer.image.width;
et orientedHeight = globalOrientation ? imgContainer.image.width : imgContainer.image.height;
`

2023-01-04 10:14 UTC, cbentejac approved these changes

2023-01-14 21:25 UTC, fabiencastan approved these changes

2023-01-14 21:25 UTC, merged