Update `ListAttributes` identically when removing edges or nodes
alicevision/Meshroom pull request #2280
Opened 2023-12-21 11:57 UTC by cbentejac

## Description

The behaviour regarding `ListAttributes` was different depending on whether an edge or a node was removed:
- if an edge was removed, the `ListAttribute` that was the destination of that edge had its corresponding element completely removed;
- if a node was removed, the `ListAttribute` that was the destination of one of the node's edges had its corresponding element reset, but not removed.

With this behaviour, a user had different UIDs depending on whether a single edge or the whole node had been removed where the UID should always be identical.

This PR ensures that removing a node has the same effect on a connected node as removing an edge: it thus removes completely an element connected to a `ListAttribute` when the node is removed.

## Implementation remarks

When collecting the outgoing edges, we now check whether the edge is connected to a `ListAttribute`. If it is, we associate the attribute of the outgoing edge to a tuple containing the `ListAttribute` it is connected to and its value (if it has any). We then remove the corresponding element in the `ListAttribute` the edge is connected to.

When recreating a node that has been removed (either by performing an "Undo" action or by upgrading a node), this map is used to check whether the edge that will be re-added is to be connected to a `ListAttribute`. If it is, a new element is added to the `ListAttribute` with the value stored in the map. Re-creating the entry in the list is necessary: if it does not exist, the edge will not have any destination attribute to connect to.

2024-01-15 11:10 UTC, cbentejac commented on meshroom/core/graph.py
> +
Save index as well

2024-01-16 11:40 UTC, fabiencastan requested changes
Need to preserve index in lists during undo

2024-01-19 15:17 UTC, cbentejac commented on meshroom/core/graph.py
> +
Done.

2024-01-31 15:07 UTC, fabiencastan approved these changes

2024-02-05 08:55 UTC, merged