Implementation of Homepage V0
alicevision/Meshroom pull request #2452
Opened 2024-06-28 14:21 UTC by Just-Kiel

## Description
First implementation of Homepage. The aim is to have something at the opening of Meshroom.

- [x] Grid view for recent projects
    - [x] Thumbnail for each project if possible
    - [x] Filestem of project
    - [x] Tooltip with the path of the project

- [x] Sponsors section with redirection to websites
- [x] Links to start section

2024-07-11 18:11 UTC, cbentejac requested changes

2024-08-09 12:50 UTC, cbentejac requested changes

2024-08-26 15:42 UTC, cbentejac approved these changes

2024-08-27 18:36 UTC, fabiencastan commented on meshroom/ui/qml/Homepage.qml
> +                        Connections {
The "Connections" may be moved at the gridView level instead of each delegate.

2024-08-30 20:55 UTC, merged