Add relative paths to nodes as variables
alicevision/Meshroom pull request #2629
Opened 2024-12-26 18:20 UTC by cbentejac

## Description

This PR adds new variables that can be used in the description of nodes to write relative paths. For each `Node` object, there are currently two variables that are available by default:
- `${NODE_CACHE_FOLDER}`, which points towards the cache folder for this node (and is effectively the same as `desc.Node.internalFolder`);
- `${NODE_SOURCECODE_FOLDER}`, which points towards the folder containing the node's description.

## Features list

## Implementation remarks

2025-01-06 15:04 UTC, fabiencastan requested changes

2025-01-06 15:04 UTC, fabiencastan commented on meshroom/core/node.py
> +        }
```suggestion
            "NODE_CACHE_FOLDER": self._internalFolder,
            "NODE_SOURCECODE_FOLDER": "UndefinedPath",
        }
```

2025-01-06 15:04 UTC, fabiencastan commented on meshroom/core/node.py
> +        }
to avoid errors

2025-01-06 17:01 UTC, cbentejac commented on meshroom/core/node.py
> +        self.rootFolder = dict()
Done

2025-01-06 17:03 UTC, cbentejac commented on meshroom/core/node.py
> +        }
Done

2025-01-06 17:55 UTC, cbentejac commented on meshroom/core/node.py
> +                            # If there is a root folder variable, substitute it before resolving the value
Done

2025-01-07 21:24 UTC, fabiencastan requested changes
Sorry, I should have seen that in the first review...

2025-01-07 21:24 UTC, fabiencastan commented on meshroom/core/desc/node.py
> +    internalFolder = '{cache}/{nodeType}/{uid}'
Do we still need it?

2025-01-07 21:24 UTC, fabiencastan commented on meshroom/core/node.py
> +
On second thought, instead of adding a new concept, these 2 variables should probably just be part of the cmdVars and used as ‘{nodeCacheFolder}’ and ‘{nodeSourceCodeFolder}’. So, we don't mix the dynamic variables and the env variables (that are static by definition).

2025-01-23 15:56 UTC, cbentejac commented on meshroom/core/desc/node.py
> +    internalFolder = '{cache}/{nodeType}/{uid}'
Removed

2025-01-23 15:56 UTC, cbentejac commented on meshroom/core/node.py
> +
Done

2025-03-07 20:29 UTC, fabiencastan approved these changes

2025-03-07 20:31 UTC, fabiencastan commented
Need update to fix the CI.

2025-03-10 10:48 UTC, merged